name      = "app"
compiler  = "g++"
version   = "c++20"

#-O
#optimize = "off"
optimize = "on"


#debug = "on"
debug = "off"

binpath = "bin/"

srcfiles = [
  "src/main.cpp",
]

# -D
defines = [
	"_CRT_SECURE_NO_WARNINGS",
]

# -I
includedirs = [
    "src/", 
    "demos/", 
    "vendor/", 
    "vendor/glad/include", 
    "vendor/stb/include", 
    "vendor/noise/", 
    "vendor/glm/", 
    "vendor/freeglut/include", 
]

# -L
libdirs = [
    "vendor/freeglut/lib"
]

# -l
libfiles = [
  "freeglut",
  "user32",
  "gdi32",
  "glu32",
  #"opengl32",
]

# -W
warnings = [
    'all'
]
