name      = "App"
compiler  = "gcc"
version   = "c++20"

#-O
#optimize = "off"
optimize = "off"

#debug = "on"
debug = "on"

binpath = "bin/"

srcfiles = [
  "src/main.cpp",
]

# -D
defines = [
	"_CRT_SECURE_NO_WARNINGS",
]

# -I
includedirs = [
  "src/", 
  "demos/", 
  "vendor/", 
  "vendor/glad/include", 
  "vendor/stb/include", 
  "vendor/noise/", 
]

# -L
libdirs = [

]

# -l
libfiles = [
  "freeglut",
  "user32",
  "gdi32",
  "glu32",
  #"opengl32",
]

# -W
warnings = [
    'all'
]
