#pragma once
#include "assets/horse_obj.h"
#include "assets/wolf_obj.h"
#include "assets/bamboo_obj.h"
#include "assets/tiger_obj.h"
#include "assets/goblin_obj.h"
#include "assets/cube_obj.h"
#include "assets/vase_plant_obj.h"
#include "assets/enemy_obj.h"